language: cpp
compiler: 
    - clang
notifications:
    email: false
before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install zlib1g-dev
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install patchelf gfortran llvm-3.2-dev libsuitesparse-dev libncurses5-dev libopenblas-dev liblapack-dev libarpack2-dev libfftw3-dev libgmp-dev libpcre3-dev libunwind7-dev libreadline-dev libdouble-conversion-dev libopenlibm-dev -y
    - sudo apt-get install julia
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e "Pkg.init()"
    - mkdir -p ~/.julia/MPC
    - mkdir -p ~/.julia/MPFR
    - git clone git://github.com/andrioni/MPFR.jl.git MPFR
    - cp -R ./* ~/.julia/MPC/
    - julia ~/.julia/MPC/test/MPC_test.jl
